# Generated by Django 4.1.5 on 2024-02-23 13:14

import contact.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('gender', models.CharField(max_length=6)),
                ('profile_picture', models.ImageField(blank=True, upload_to=contact.utils.pfp_handle)),
            ],
        ),
    ]
